# Generated by Django 5.2.17 on 2026-09-03 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('phone', models.CharField(help_text='Formato E.164, ex: +5511999998888', max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('tags', models.CharField(blank=True, help_text='separadas por vírgula', max_length=255, verbose_name='tags')),
                ('consent_given', models.BooleanField(default=False, verbose_name='consentimento registrado')),
                ('consent_source', models.CharField(blank=True, max_length=160, verbose_name='origem do consentimento')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='consentimento em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_contacts', to=settings.AUTH_USER_MODEL, verbose_name='importado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tenants.organization', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'phone'), name='unique_phone_per_organization')],
            },
        ),
    ]
