# Generated by Django 5.2.17 on 2026-09-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='opted_out',
            field=models.BooleanField(default=False, help_text="Contato pediu para parar de receber mensagens (respondeu 'Parar' em alguma campanha).", verbose_name='descadastrado'),
        ),
    ]
