# Generated by Django 5.2.17 on 2026-09-03 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0006_campaign_scheduled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('saida', 'Equipe'), ('entrada', 'Contato (simulado)')], max_length=10, verbose_name='direção')),
                ('body', models.TextField(verbose_name='mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('dispatch_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaigns.dispatchlog', verbose_name='atendimento')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='enviada por')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['created_at'],
            },
        ),
    ]
