# Generated by Django 5.2.17 on 2026-09-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='test_recipient_phones',
            field=models.CharField(blank=True, help_text='Telefones em E.164 separados por vírgula liberados para receber envios quando WHATSAPP_SEND_MODE=test, ex: +5511999998888,+5511988887777', max_length=255, verbose_name='números de teste'),
        ),
    ]
