# Generated by Django 5.2.17 on 2026-09-03 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('tenants', '0002_organization_test_recipient_phones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('segment_tag', models.CharField(blank=True, help_text='Deixe em branco para enviar a todos os contatos com consentimento.', max_length=100, verbose_name='segmento (tag)')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('concluida', 'Concluída')], default='rascunho', max_length=20, verbose_name='status')),
                ('send_mode_used', models.CharField(blank=True, max_length=20, verbose_name='modo de envio usado')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='disparada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='tenants.organization', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'campanha',
                'verbose_name_plural': 'campanhas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('message_body', models.TextField(verbose_name='mensagem enviada')),
                ('status', models.CharField(choices=[('simulado', 'Simulado'), ('teste_enviado', 'Enviado (teste)'), ('bloqueado', 'Bloqueado')], max_length=20, verbose_name='status')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='detalhe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='campaigns.campaign', verbose_name='campanha')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='contacts.contact', verbose_name='contato')),
            ],
            options={
                'verbose_name': 'registro de disparo',
                'verbose_name_plural': 'registros de disparo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('body', models.TextField(help_text='Use {{nome}} e {{telefone}} para personalizar cada envio.', verbose_name='mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='tenants.organization', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'template de mensagem',
                'verbose_name_plural': 'templates de mensagem',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.messagetemplate', verbose_name='template'),
        ),
    ]
