# Generated by Django 5.2.17 on 2026-09-03 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateButton',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20, verbose_name='texto')),
                ('action', models.CharField(choices=[('prosseguir', 'Prosseguir (transfere ao atendente)'), ('parar', 'Parar (bloqueia o contato)')], default='prosseguir', max_length=20, verbose_name='ação')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='campaigns.messagetemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'botão de decisão',
                'verbose_name_plural': 'botões de decisão',
                'ordering': ['order'],
            },
        ),
    ]
