# Generated by Django 5.2.17 on 2026-09-03 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_templatebutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchlog',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='respondido em'),
        ),
        migrations.AddField(
            model_name='dispatchlog',
            name='response_button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='campaigns.templatebutton', verbose_name='botão respondido'),
        ),
    ]
