# Generated by Django 5.2.17 on 2026-09-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_dispatchlog_responded_at_dispatchlog_response_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchlog',
            name='status',
            field=models.CharField(choices=[('simulado', 'Simulado'), ('teste_enviado', 'Enviado (teste)'), ('bloqueado', 'Bloqueado'), ('falhou', 'Falhou')], max_length=20, verbose_name='status'),
        ),
    ]
