# Generated by Django 5.2.17 on 2026-09-03 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_dispatchlog_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchlog',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='atendimento assumido em'),
        ),
        migrations.AddField(
            model_name='dispatchlog',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL, verbose_name='atendido por'),
        ),
    ]
