# Generated by Django 5.2.17 on 2026-09-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_dispatchlog_assigned_at_dispatchlog_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='agendada para'),
        ),
    ]
